//all needed data is stored in the file, to easily extend or change any asset
export const charsConfig = {
    babaYaga: {
        loopCam: 'BabaYaga',
        asset: 'BabaYaga',
        setScale: true,
        scale: 46,
        setPosition: true,
        xPosition: 3.6,
        yPosition: 0.5,
        zPosition: 3,
        setRotation: true,
        axis: 'Y',
        rotation: -45 / Math.PI,
        boxPosition: 'left',
        ar: {
            lightPosition: '0 15 0',
            rotation: '45 90 -90',
            scale: '40 40 40',
            position: '0 0 1.5',
            lightIntensity: 2.5,
        }
    },
    basilisk: {
        loopCam: 'Basilisk',
        asset: 'Basilisk',
        setScale: true,
        scale: 210,
        setPosition: true,
        xPosition: 2.9,
        yPosition: -3,
        zPosition: 2,
        setRotation: true,
        axis: 'Y',
        rotation: 32 / Math.PI,
        boxPosition: 'left',
        ar: {
            lightPosition: '0 10 -5',
            rotation: '90 90 -90',
            scale: '60 60 60',
            position: '0 0 1',
            lightIntensity: 2.5,
        }
    },
    baum: {
        loopCam: 'Baum',
        asset: 'Baum',
        setScale: true,
        scale: '0',
        setPosition: false,
        xPosition: '',
        yPosition: '',
        zPosition: '',
        setRotation: false,
        axis: '',
        rotation: '',
        boxPosition: 'left',
        ar: {
            lightPosition: '0 10 -5',
            rotation: '90 90 -90',
            scale: '0.2 0.2 0.2',
            position: '0 0 1.5',
            lightIntensity: 1.5,
        }
    },
    eier: {
        loopCam: 'Eier',
        asset: 'Eier',
        setScale: true,
        scale: 46,
        setPosition: true,
        xPosition: -4.8,
        yPosition: -3,
        zPosition: 3,
        setRotation: true,
        axis: 'Y',
        rotation: 57 / Math.PI,
        boxPosition: 'right',
        ar: {
            lightPosition: '0 10 -10',
            rotation: '-90 90 -90',
            scale: '20 20 20',
            position: '0 0 1',
            lightIntensity: 1,
        }
    },
    jobold: {
        loopCam: 'Jobold',
        asset: 'Jobold',
        setScale: true,
        scale: '35',
        setPosition: true,
        xPosition: '',
        yPosition: '-2',
        zPosition: '',
        setRotation: false,
        axis: '',
        rotation: '',
        boxPosition: 'left',
        ar: {
            lightPosition: '1 20 5',
            rotation: '-90 90 -90',
            scale: '15 15 15',
            position: '0 0 1',
            lightIntensity: 2,
        }
    },
    main: {
        loopCam: 'Main',
        asset: 'Chupacabra',
        setScale: true,
        scale: 3,
        setPosition: true,
        xPosition: 3,
        yPosition: -2,
        zPosition: 2,
        setRotation: true,
        axis: "Y",
        rotation: 31.5 / Math.PI,
        boxPosition: 'left',
        ar: {
            lightPosition: '0 5 0',
            rotation: '90 90 -92',
            scale: '1.5 1.5 1.5',
            position: '0 0 1',
            lightIntensity: "2.5",
        }
    },
    nessie: {
        loopCam: 'Nessie',
        asset: 'Nessie',
        setScale: true,
        scale: 35,
        setPosition: true,
        xPosition: 0.5,
        yPosition: -2.4,
        zPosition: -1,
        setRotation: true,
        axis: "Y",
        rotation: Math.PI / 3.5,
        boxPosition: 'left',
        ar: {
            lightPosition: '0 5 0',
            rotation: '-110 90 -90',
            scale: '15 15 15',
            position: '0 0 1',
            lightIntensity: 2.5,
        }
    },
    wolpertinger: {
        loopCam: 'Wolpertinger',
        asset: 'Wolpertinger',
        setScale: true,
        scale: 46,
        setPosition: true,
        xPosition: -0.2,
        yPosition: -1.2,
        zPosition: -1,
        setRotation: false,
        axis: '',
        rotation: '',
        boxPosition: 'left',
        ar: {
            lightPosition: '0 5 0',
            rotation: '-90 90 -90',
            scale: '20 20 20',
            position: '0 0 1',
            lightIntensity: 1,
        }
    },
    yeti: {
        loopCam: 'Yeti',
        asset: 'Yeti',
        setScale: true,
        scale: 50,
        setPosition: true,
        xPosition: 0.5,
        yPosition: -2.4,
        zPosition: -1,
        setRotation: false,
        axis: '',
        rotation: '',
        boxPosition: 'left',
        ar: {
            lightPosition: '0 10 -5',
            rotation: '-90 90 -90',
            scale: '20 20 20',
            position: '0 0 1',
            lightIntensity: 1.2,
        }
    }
};