export const charsConfig = {
    babaYaga: {
        loopCam: 'BabaYaga',
        asset: 'BabaYaga',
        setScale: false,
        scale: '',
        setPosition: false,
        xPosition: '',
        yPosition: '',
        zPosition: '',
        setRotation: false,
        axis: '',
        rotation: '',
        boxPosition: 'left',
        ar: {
            lightPosition: '0 0 0',
            rotation: '0 0 0',
            scale: '0 0 0',
            position: '0 0 0',
        }
    },
    basilisk: {
        loopCam: 'Basilisk',
        asset: 'Basilisk',
        setScale: false,
        scale: '',
        setPosition: false,
        xPosition: '',
        yPosition: '',
        zPosition: '',
        setRotation: false,
        axis: '',
        rotation: '',
        boxPosition: 'left',
        ar: {
            lightPosition: '0 0 0',
            rotation: '0 0 0',
            scale: '0 0 0',
            position: '0 0 0',
        }
    },
    baum: {
        loopCam: 'Baum',
        asset: 'Baum',
        setScale: false,
        scale: '',
        setPosition: false,
        xPosition: '',
        yPosition: '',
        zPosition: '',
        setRotation: false,
        axis: '',
        rotation: '',
        boxPosition: 'left',
        ar: {
            lightPosition: '0 0 0',
            rotation: '0 0 0',
            scale: '0 0 0',
            position: '0 0 0',
        }
    },
    eier: {
        loopCam: 'Eier',
        asset: 'Eier',
        setScale: false,
        scale: '',
        setPosition: false,
        xPosition: '',
        yPosition: '',
        zPosition: '',
        setRotation: false,
        axis: '',
        rotation: '',
        boxPosition: 'right',
        ar: {
            lightPosition: '0 0 0',
            rotation: '0 0 0',
            scale: '0 0 0',
            position: '0 0 0',
        }
    },
    jobold: {
        loopCam: 'Jobold',
        asset: 'Jobold',
        setScale: false,
        scale: '',
        setPosition: false,
        xPosition: '',
        yPosition: '',
        zPosition: '',
        setRotation: false,
        axis: '',
        rotation: '',
        boxPosition: 'left',
        ar: {
            lightPosition: '0 0 0',
            rotation: '0 0 0',
            scale: '0 0 0',
            position: '0 0 0',
        }
    },
    main: {
        loopCam: 'Main',
        asset: 'Chupacabra',
        setScale: true,
        scale: 3,
        setPosition: true,
        xPosition: 3,
        yPosition: -2,
        zPosition: 2,
        setRotation: true,
        axis: "Y",
        rotation: 31.5 / Math.PI,
        boxPosition: 'left',
        ar: {
            lightPosition: '0 5 0',
            rotation: '90 90 -90',
            scale: '1.5 1.5 1.5',
            position: '0 0 1',
        }
    },
    nessie: {
        loopCam: 'Nessie',
        asset: 'Nessie',
        setScale: true,
        scale: 35,
        setPosition: true,
        xPosition: 0.5,
        yPosition: -2.4,
        zPosition: -1,
        setRotation: true,
        axis: "Y",
        rotation: Math.PI / 3.5,
        boxPosition: 'left',
        ar: {
            lightPosition: '0 0 0',
            rotation: '0 0 0',
            scale: '0 0 0',
            position: '0 0 0',
        }
    },
    wolpertinger: {
        loopCam: 'Wolpertinger',
        asset: 'Wolpertinger',
        setScale: true,
        scale: 46,
        setPosition: true,
        xPosition: -0.2,
        yPosition: -1.2,
        zPosition: -1,
        setRotation: false,
        axis: '',
        rotation: '',
        boxPosition: 'left',
        ar: {
            lightPosition: '0 0 0',
            rotation: '0 0 0',
            scale: '0 0 0',
            position: '0 0 0',
        }
    },
    yeti: {
        loopCam: 'Yeti',
        asset: 'Yeti',
        setScale: true,
        scale: 50,
        setPosition: true,
        xPosition: 0.5,
        yPosition: -2.4,
        zPosition: -1,
        setRotation: false,
        axis: '',
        rotation: '',
        boxPosition: 'left',
        ar: {
            lightPosition: '0 0 0',
            rotation: '0 0 0',
            scale: '0 0 0',
            position: '0 0 0',
        }
    }
};